version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nasu-pulsarr_server_1
      APP_PORT: 3003
      PROXY_AUTH_ADD: 'false'
    
  server:
    image: lakker/pulsarr:v0.11.5
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/.env:/app/.env
    environment:
      - TZ=Europe/London
      - baseUrl=http://192.168.1.140
      - port=3003
    user: "1000:1000"
    init: true
    restart: on-failure
