version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nasu-pulsarr_server_1
      APP_PORT: 3003
    
  server:
    image: lakker/pulsarr:latest
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/.env:/app/.env
    environment:
      - TZ=Europe/London
    user: "1000:1000"
    init: true
    restart: on-failure
