version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nasu-suwayomi_web_1
      APP_PORT: 4567
    
  web:
    image: ghcr.io/suwayomi/suwayomi-server:v2.1.1867@sha256:acad9ea1cbb968bc95477a69e32dbc682b710a00ed6e7b06f0eb167caf382e81
    environment:
      - TZ=Europe/London
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/suwayomi/.local/share/Tachidesk
      #ROB YOU NEED TO CHOWN THIS DIRECTORY. ROB. DO IT.
    user: "1000:1000"
    init: true
    restart: on-failure

  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    restart: unless-stopped