version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: nasu-suwayomi_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'
    container_name: nasu-suwayomi_app_proxy_1
  web:
    image: >-
      ghcr.io/suwayomi/suwayomi-server:preview
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/suwayomi/.local/share/Tachidesk:rw
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
    container_name: nasu-suwayomi_web_1
