version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nasu-suwayomi_server_1
      APP_PORT: 3000
    
  server:
    image: ghcr.io/suwayomi/suwayomi-server:v2.1.1867@sha256:acad9ea1cbb968bc95477a69e32dbc682b710a00ed6e7b06f0eb167caf382e81
    environment:
      - TZ=Europe/London
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/suwayomi/.local/share/Tachidesk:rw
    user: "1000:1000"
    init: true
